spring:
  datasource:
    url: jdbc:postgresql://dpg-d3v7g0d13ps73fk8n70-a.frankfurt-postgres.render.com:5432/wishlist_db_c91n
    username: wishlist_db_c91n_user
    password: KywLQMtR1wmv9xRRQE5orcWLdiZOrWi
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: noellesecret01@gmail.com
    password: flxu qjzk aygm vupp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
        debug: true


key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

logging:
  file:
    name: logs/log.log
  level:
    root: info

app:
  base-url: http://localhost:8080
