spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_wishlist
    username: ania
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: qwert007
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: noellesecret01@gmail.com
    password: flxu qjzk aygm vupp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
        debug: true

key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

logging:
  file:
    name: logs/log.log
  level:
    root: info

app:
  base-url: http://localhost:8080