spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: giflistify@gmail.com
    password: cctjikrhnlabrbky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
        debug: true


key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

app:
  base-url: https://project-wishlist-giftlistify-ccqrj.ondigitalocean.app
